In [1]:
import mediapipe as mep

In [2]:
import cv2

In [3]:
import numpy as np
import pandas as pd

In [4]:
mep_drw = mep.solutions.drawing_utils
mep_ps = mep.solutions.pose

def cal_angle(a,b,c):
    a=np.array(a)
    b=np.array(b)
    c=np.array(c)
    
    radians=np.arctan2(c[1]-b[1],c[0]-b[0]) - np.arctan2(a[1]-b[1],a[0]-b[0])
    angle=np.abs(radians*180.0/np.pi)
    
    if angle>180.0:
        angle=360-angle
    
    return angle

In [5]:
mep_ps

<module 'mediapipe.python.solutions.pose' from 'C:\\Users\\p\\OneDrive\\anaconda\\lib\\site-packages\\mediapipe\\python\\solutions\\pose.py'>

In [6]:
capt = cv2.VideoCapture(0)
with mep_ps.Pose(min_detection_confidence=0.5,min_tracking_confidence=0.5) as pose:
    while True:
        ret, frame = capt.read()
        im = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
        im.flags.writeable = False
        re = pose.process(im)
        im.flags.writeable = True
        im = cv2.cvtColor(im,cv2.COLOR_RGB2BGR)
        #extract landmarks
        try:
            landmarks = re.pose_landmarks.landmark
            #get cord
            rt_hip = [landmarks[mep_ps.PoseLandmark.RIGHT_HIP].x,landmarks[mep_ps.PoseLandmark.RIGHT_HIP].y]
            rt_kne = [landmarks[mep_ps.PoseLandmark.RIGHT_KNEE].x,landmarks[mep_ps.PoseLandmark.RIGHT_KNEE].y]
            rt_toe = [landmarks[mep_ps.PoseLandmark.RIGHT_HEEL].x,landmarks[mep_ps.PoseLandmark.RIGHT_HEEL].y]
            
            lt_hip = [landmarks[mep_ps.PoseLandmark.LEFT_HIP].x,landmarks[mep_ps.PoseLandmark.LEFT_HIP].y]
            lt_kne = [landmarks[mep_ps.PoseLandmark.LEFT_KNEE].x,landmarks[mep_ps.PoseLandmark.LEFT_KNEE].y]
            lt_toe = [landmarks[mep_ps.PoseLandmark.LEFT_HEEL].x,landmarks[mep_ps.PoseLandmark.LEFT_HEEL].y]
            
            
            #Cal ang
            rt_angle = cal_angle(rt_hip,rt_knw,rt_toe)
            cv2.putText(im,str(angle),tuple(np.multiply(lb,[640,480]).astype(int)),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2,cv2.LINE_AA
                       
                       )
            lt_angle = cal_angle(lt_hip,lt_kne,lt_toe)
            cv2.putText(im,str(angle2),tuple(np.multiply(kne,[640,480]).astype(int)),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2,cv2.LINE_AA
                       
                       )
            
                
        except:
            pass
        mep_drw.draw_landmarks(im,re.pose_landmarks,mep_ps.POSE_CONNECTIONS,
                             mep_drw.DrawingSpec(color=(245,117,66),thickness=2,
                                          circle_radius=2),mep_drw.DrawingSpec(color=(266,167,56),thickness=2,
                                          circle_radius=2))
        #print(res)
        cv2.imshow('Video',im)
        key = cv2.waitKey(1) & 0xFF

        if key == ord("q"):
            break
capt.release()
cv2.destroyAllWindows()

In [7]:
landmarks

[x: 0.45636096596717834
y: 0.718473494052887
z: -1.3522794246673584
visibility: 0.9971486926078796
, x: 0.4782721996307373
y: 0.6286859512329102
z: -1.2704946994781494
visibility: 0.9965251088142395
, x: 0.49713462591171265
y: 0.6236154437065125
z: -1.2711182832717896
visibility: 0.9970744848251343
, x: 0.5130006670951843
y: 0.619925320148468
z: -1.2713892459869385
visibility: 0.9963311553001404
, x: 0.4051899015903473
y: 0.6527110934257507
z: -1.2702564001083374
visibility: 0.9965054392814636
, x: 0.3799877166748047
y: 0.6616848111152649
z: -1.2701199054718018
visibility: 0.9970315098762512
, x: 0.35976147651672363
y: 0.6694355607032776
z: -1.2707947492599487
visibility: 0.9966229796409607
, x: 0.5364066362380981
y: 0.6462463140487671
z: -0.7319626808166504
visibility: 0.9977000951766968
, x: 0.33180302381515503
y: 0.7119211554527283
z: -0.7168235778808594
visibility: 0.9972473382949829
, x: 0.5034778118133545
y: 0.7891870141029358
z: -1.1472059488296509
visibility: 0.997083842754364


In [8]:
a =np.multiply(rt_hip,[640,480]).astype(int)
b = np.multiply(rt_kne,[640,480]).astype(int)
c=np.multiply(rt_toe,[640,480]).astype(int)
d=np.multiply(lt_hip,[640,480]).astype(int)
e=np.multiply(lt_kne,[640,480]).astype(int)
f= np.multiply(lt_toe,[640,480]).astype(int)

In [9]:
li =[a,b,c,d,e,f]

In [10]:
data_frame= pd.DataFrame(data = li, columns= ["x", "y"])

In [11]:
data_frame

x     y
0  267   968
1  312  1296
2  358  1674
3  482   948
4  510  1291
5  558  1663

In [12]:
data_frame.to_excel('Body_Posture.xlsx')

In [13]:
landmarks[mep_ps.PoseLandmark.RIGHT_HIP]
np.multiply(rt_hip,[640,480]).astype(int)

array([267, 968])

In [14]:
landmarks[mep_ps.PoseLandmark.RIGHT_KNEE]
np.multiply(rt_kne,[640,480]).astype(int)

array([ 312, 1296])

In [15]:
landmarks[mep_ps.PoseLandmark.RIGHT_HEEL]
np.multiply(rt_toe,[640,480]).astype(int)

array([ 358, 1674])

In [16]:
landmarks[mep_ps.PoseLandmark.LEFT_HIP]
np.multiply(lt_hip,[640,480]).astype(int)

array([482, 948])

In [17]:
landmarks[mep_ps.PoseLandmark.LEFT_KNEE]
np.multiply(lt_kne,[640,480]).astype(int)

array([ 510, 1291])

In [18]:
landmarks[mep_ps.PoseLandmark.LEFT_HEEL]
np.multiply(lt_toe,[640,480]).astype(int)

array([ 558, 1663])